# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)

1.19.2


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
X = np.zeros(10)
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
X = np.array([10,20,30])
X.size

3

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [6]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

Exception: File `'`python.py'` not found.

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [10]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [12]:
b= np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [13]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [16]:
c= np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [18]:
no_ze = np.nonzero([1,2,0,0,4,0])
no_ze

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [19]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [20]:
print(np.random.random((3,3,3)))

[[[0.67669271 0.1580687  0.68582783]
  [0.59166824 0.09436999 0.97554194]
  [0.89261271 0.40222567 0.07080371]]

 [[0.50628424 0.58984154 0.16831966]
  [0.24338141 0.9822602  0.79648032]
  [0.35578638 0.64586203 0.89683901]]

 [[0.5799103  0.86876897 0.17624143]
  [0.06091212 0.4127731  0.67959806]
  [0.26685533 0.36416702 0.71226537]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [21]:
l = np.random.random((10,10))
lmin,lmax = l.min(), l.max()
print(lmin, lmax)

0.024339255424609463 0.9915353528980058


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [25]:
g = np.random.random(30)
g.mean()

0.5292978546385038

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [28]:
g = np.ones((10,10))
g[1:-1,1:-1]=0
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [7]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [30]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [31]:
np.diag(1+np.arange(4), k= -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [33]:
a =np.zeros((8,8), dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [34]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [35]:
ar = np.array([[0,1],[1,0]])
f = np.tile(ar, (4,4))
f

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [36]:
n = np.random.random((5,5))
nmax,nmin = n.max(), n.min()
n = (n-nmin)/(nmax - nmin)
n

array([[0.91917385, 0.08203194, 0.1311902 , 1.        , 0.29439369],
       [0.92084728, 0.08932557, 0.07663041, 0.57617154, 0.68472254],
       [0.20141679, 0.07297614, 0.26468442, 0.17384945, 0.35399285],
       [0.44242818, 0.93430276, 0.08247444, 0.        , 0.35740752],
       [0.50384143, 0.18459193, 0.69766661, 0.54730188, 0.52458551]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [10]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
color

C:\Users\Alan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [11]:
np.ones((5,3)) @ np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [12]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [13]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [14]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [15]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Alan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Alan\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [16]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  2.   7. -10.   9.   7.   8.   4.  -5.  -1.   9.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [17]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(np.intersect1d(a1,a2))

[0 2 3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [21]:
defaults = np.seterr(all="ignore")
f = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    f = np.ones(1) / 0
f

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [22]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Alan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [26]:
yest= np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today= np.datetime64('today', 'D')
tmw= np.datetime64('today', 'D') + np.timedelta64(1, 'D')
#yest
today
#tmw

numpy.datetime64('2021-09-28')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [27]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [28]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [29]:
j = np.random.uniform(0,10,10)

print (j - j%1)
print (np.floor(j))
print (np.ceil(j)-1)
print (j.astype(int))
print (np.trunc(j))

[9. 8. 8. 4. 6. 5. 5. 1. 3. 4.]
[9. 8. 8. 4. 6. 5. 5. 1. 3. 4.]
[9. 8. 8. 4. 6. 5. 5. 1. 3. 4.]
[9 8 8 4 6 5 5 1 3 4]
[9. 8. 8. 4. 6. 5. 5. 1. 3. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [30]:
k = np.zeros((5,5))
k += np.arange(5)
k

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [31]:
def generator():
    for x in range(10):
        yield x
p = np.fromiter(generator(),dtype=float,count=-1)
p

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [32]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [33]:
a = np.random.random(10)
a.sort()
a

array([0.03087775, 0.06779549, 0.19156175, 0.19825307, 0.23658107,
       0.34536615, 0.39869533, 0.78099507, 0.87181164, 0.90515896])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [34]:
l = np.arange(10)
np.add.reduce(l)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [38]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
eq = np.allclose(A,B)
print(eq)
eq = np.array_equal(a,b)
print(eq)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [39]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [40]:
a = np.random.random((10,2))
x,y = a[:,0], a[:,1]
s = np.sqrt(x**2+y**2)
d = np.arctan2(y,x)
print(s)
print(d)

[0.81246958 0.71134697 0.82815722 0.93916549 0.78018238 0.6387283
 0.84531964 0.97559629 1.24020433 0.60931314]
[0.61656006 0.46593039 0.4951768  0.26787303 0.34862384 1.12876001
 1.44972208 0.886648   0.70622321 1.37607486]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [41]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.13956137, 0.33638903, 0.12666925, 0.69578375, 0.17147126,
       0.73766058, 0.60093773, 0.75546228, 0.        , 0.11067275])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [43]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [45]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [52]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [53]:
np.set_printoptions(threshold=np.nan)
A = np.zeros((16,16))
print(A)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(a-v)).argmin()
print(a[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [4]:
np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])

C:\Users\Alan\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [3]:
import scipy
import scipy.spatial

a = np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

a = np.random.random((10,2))
d = scipy.spatial.distance.cdist(a,a)
print(a)

[[0.         0.57639237 0.34134357 0.634613   0.70251876 0.94287695
  0.82082522 0.75329069 0.3690257  0.82828898]
 [0.57639237 0.         0.38552258 0.06535587 0.14611014 0.46531626
  0.25473339 0.37331338 0.21783316 0.46159699]
 [0.34134357 0.38552258 0.         0.41888414 0.45915601 0.62681775
  0.57225339 0.42409972 0.29337352 0.7971418 ]
 [0.634613   0.06535587 0.41888414 0.         0.0812663  0.40554041
  0.19042429 0.33377711 0.28162335 0.48066977]
 [0.70251876 0.14611014 0.45915601 0.0812663  0.         0.32819448
  0.11863848 0.28521962 0.35880949 0.52644668]
 [0.94287695 0.46531626 0.62681775 0.40554041 0.32819448 0.
  0.27975872 0.21206231 0.65342815 0.82326209]
 [0.82082522 0.25473339 0.57225339 0.19042429 0.11863848 0.27975872
  0.         0.3196013  0.47203464 0.54354021]
 [0.75329069 0.37331338 0.42409972 0.33377711 0.28521962 0.21206231
  0.3196013  0.         0.51058079 0.81002589]
 [0.3690257  0.21783316 0.29337352 0.28162335 0.35880949 0.65342815
  0.47203464 0.51058

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [5]:
a = np.arange(10, dtype=np.float32)
a = a.astype(np.int32, copy=False)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [6]:
from io import StringIO
a = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
b = np.genfromtxt(a, delimiter=",", dtype=np.int)
print(b)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [7]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [8]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [9]:
a = 10
b = 3
x = np.zeros((a,a))
np.put(x, np.random.choice(range(a*a), b, replace=False),1)
print(x)

[[0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [11]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[-0.02082934, -0.09691543,  0.12396401,  0.28619522, -0.55988301,
        -0.10797489,  0.15098086,  0.18940479,  0.32989672, -0.29483893],
       [-0.36127598,  0.03478529,  0.42161373,  0.03301023,  0.26087849,
        -0.23477752, -0.21543508, -0.08328864, -0.15359139,  0.29808086],
       [ 0.07317767,  0.34208694,  0.52931004, -0.19601312, -0.13391042,
        -0.36593582,  0.03923398, -0.18680186,  0.0469419 , -0.14808931],
       [ 0.38299413,  0.39493968,  0.44269389, -0.23517901, -0.18792314,
        -0.02409577, -0.08694983, -0.38900294, -0.12084303, -0.17663399],
       [ 0.5686217 , -0.15320868, -0.10942424, -0.15730246,  0.33340137,
         0.40524777, -0.20371702, -0.18272006, -0.20238665, -0.29851172]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [12]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[6 6 6]
 [5 6 6]
 [2 5 9]]
[[2 5 9]
 [6 6 6]
 [5 6 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [13]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [14]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4707461777512897


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [15]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [16]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [17]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 3. 4. 5. 1. 3. 2. 2. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [18]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [20]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [21]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[50 63 47 55]
 [47 51 58 43]
 [43 72 50 37]]
[[50 63 47 55]
 [47 51 58 43]
 [43 72 50 37]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [22]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.36737927 0.55176518 0.41443869 0.54008907 0.4673016  0.45681846
 0.65259866 0.54093124 0.69858721 0.53199416]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [23]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5)) 
np.diag(np.dot(A, B))

array([1.57133356, 0.57477548, 0.43059144, 0.73504622, 0.9976082 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [24]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [25]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [26]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [27]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 36) ( 4, 47) ( 4, 60) ( 4, 79) ( 5, 54) ( 5, 75) ( 6, 29) ( 6, 62)
 ( 7, 27) ( 7, 55) (12, 48) (12, 53) (24, 57) (24, 65) (27, 55) (29, 62)
 (30, 34) (30, 95) (34, 95) (36, 79) (38, 46) (38, 92) (43, 53) (43, 98)
 (46, 92) (47, 60) (48, 53) (53, 98) (54, 75) (57, 65)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [28]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [29]:
def average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [30]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [31]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-3.73993993e-01, -4.51962374e-01,  8.67642463e-01, -3.63628512e-01,
        5.21230986e-01, -1.27957799e-01, -3.81609307e-01, -2.40153933e-01,
        7.21569648e-01,  8.51516187e-01, -4.19801239e-01, -8.21512930e-01,
       -6.82239253e-01,  7.74647766e-01, -3.04530065e-01, -2.90751225e-01,
        6.94491368e-01,  9.34749070e-01, -9.85656170e-01, -8.98159726e-01,
       -2.50791478e-02, -9.73764096e-01, -5.42723957e-01, -9.99908929e-01,
       -5.49758114e-01, -4.95634249e-01,  1.16905204e-01, -1.39947361e-01,
        2.18032567e-01,  7.00878949e-01,  3.32503138e-01, -8.01865398e-01,
       -7.07103015e-02,  2.66579049e-01, -3.32964801e-01, -6.00590653e-02,
       -4.06734503e-01,  9.42901173e-01, -4.81034972e-01, -6.01807965e-01,
       -7.34399656e-01, -9.29783062e-01, -8.21243797e-01, -1.78362636e-01,
        5.72059451e-01,  8.98073704e-01,  3.41726721e-01, -4.99610597e-02,
       -5.40154189e-01,  9.76198346e-01, -3.81449651e-05,  2.20412166e-01,
        7.15065547e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [32]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.41257203  0.48834013  8.76951906  5.80016132 14.37334305  7.26905937
  2.75465684  1.40324418 18.63016048  6.26224901]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [34]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[8.89688317e-02 5.39839328e+00 1.52537682e-02 1.02177535e+00
  1.64242082e+00 3.73202879e+00 1.44558320e+00 4.75623437e+00
  3.30498163e+00 1.88156136e+00]
 [3.81139023e+00 3.65740131e+00 5.43650223e+00 2.40117831e+00
  1.47570674e+01 1.58774100e+01 4.22531016e+00 1.12614863e+00
  1.20287984e+01 1.71036063e+01]
 [9.88505258e+00 4.85555103e+00 1.00505775e+01 9.36223385e+00
  6.22783013e+00 4.27096782e+00 1.14725247e+01 4.81555416e+00
  6.03848500e+00 6.69096769e+00]
 [1.22119982e+01 5.77245122e+00 6.31404003e+00 8.24730684e+00
  4.53249551e+00 3.79477184e+00 7.57446711e+00 8.43979155e+00
  1.69549693e-01 1.64884561e+01]
 [5.78127527e-01 4.58832055e+00 1.17045389e+00 2.93272685e-02
  2.94544048e+00 2.36021669e+00 2.64152890e+00 4.23320199e+00
  2.00219097e+00 1.47258390e+00]
 [7.83706070e+00 1.35280275e+01 8.51143714e+00 9.48180505e+00
  3.23541056e+00 1.10537193e+01 7.03734498e+00 1.20371371e+01
  1.14584368e+01 8.89621182e-01]
 [1.41848304e+01 7.77083980e+00 8.18207804e+00 1.02297528e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [35]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 6 2 7 0 8 8 5 5 5]
 [9 3 8 6 1 0 6 0 2 3]
 [5 0 5 2 2 0 9 6 7 5]
 [1 5 7 9 1 6 4 2 2 0]
 [7 4 6 5 6 6 5 5 8 9]
 [8 4 3 2 9 6 0 0 4 6]
 [9 5 9 2 7 1 1 4 1 7]
 [7 0 9 0 4 9 8 7 0 7]
 [6 5 5 3 5 9 8 6 3 1]
 [6 3 5 5 2 4 1 4 5 5]]
[[0 0 0 0 0]
 [0 4 6 2 7]
 [0 9 3 8 6]
 [0 5 0 5 2]
 [0 1 5 7 9]]


C:\Users\Alan\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [36]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [2]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [3]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [5]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 1 4]
   [3 2 4]
   [2 2 4]]

  [[1 4 0]
   [2 4 4]
   [2 4 4]]

  [[4 0 1]
   [4 4 3]
   [4 4 1]]

  [[0 1 2]
   [4 3 0]
   [4 1 2]]

  [[1 2 4]
   [3 0 3]
   [1 2 3]]

  [[2 4 4]
   [0 3 0]
   [2 3 0]]

  [[4 4 0]
   [3 0 1]
   [3 0 2]]

  [[4 0 1]
   [0 1 3]
   [0 2 3]]]


 [[[3 2 4]
   [2 2 4]
   [4 3 3]]

  [[2 4 4]
   [2 4 4]
   [3 3 0]]

  [[4 4 3]
   [4 4 1]
   [3 0 4]]

  [[4 3 0]
   [4 1 2]
   [0 4 3]]

  [[3 0 3]
   [1 2 3]
   [4 3 0]]

  [[0 3 0]
   [2 3 0]
   [3 0 4]]

  [[3 0 1]
   [3 0 2]
   [0 4 4]]

  [[0 1 3]
   [0 2 3]
   [4 4 3]]]


 [[[2 2 4]
   [4 3 3]
   [3 2 3]]

  [[2 4 4]
   [3 3 0]
   [2 3 1]]

  [[4 4 1]
   [3 0 4]
   [3 1 4]]

  [[4 1 2]
   [0 4 3]
   [1 4 4]]

  [[1 2 3]
   [4 3 0]
   [4 4 3]]

  [[2 3 0]
   [3 0 4]
   [4 3 0]]

  [[3 0 2]
   [0 4 4]
   [3 0 3]]

  [[0 2 3]
   [4 4 3]
   [0 3 4]]]


 [[[4 3 3]
   [3 2 3]
   [3 0 1]]

  [[3 3 0]
   [2 3 1]
   [0 1 0]]

  [[3 0 4]
   [3 1 4]
   [1 0 2]]

  [[0 4 3]
   [1 4 4]
   [0 2 0]]

  [[4 3 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [6]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1  9  7  8  8]
 [ 9  1 10  7  6]
 [ 7 10  6 42 12]
 [ 8  7 42  0 17]
 [ 8  6 12 17  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [7]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [9]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [10]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] + Z[1:-1,0:-2] + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [11]:
a = np.arange(10000)
np.random.shuffle(a)
b= 5
print (a[np.argsort(a)[-b:]])
print (a[np.argpartition(-a,b)[:b]])

[9995 9996 9997 9998 9999]
[9998 9995 9999 9997 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [14]:
def cart(arr):
    arr = [np.asarray(a) for a in arr]
    shape = (len(x) for x in arr)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arr), -1).T

    for n, arrays in enumerate(arr):
        ix[:, n] = arr[n][ix[:, n]]

    return ix

print (cart(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [15]:
a = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
b = np.core.records.fromarrays(a.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(b)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [16]:
a = np.random.rand(5e7)

%timeit np.power(a,3)
%timeit a*a*a
%timeit np.einsum('i,i,i->i',a,a,a)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [18]:
x = np.random.randint(0,5,(8,3))
y = np.random.randint(0,5,(2,2))

z = (x[..., np.newaxis, np.newaxis] == y)
row = np.where(z.any((3,1)).all(1))[0]
print(row)

[2 3 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [19]:
a = np.random.randint(0,5,(10,3))
print(a)
b = np.all(a[:,1:] == a[:,:-1], axis=1)
c = a[~b]
print(c)
c = a[a.max(axis=1) != a.min(axis=1),:]
print(c)

[[3 1 0]
 [1 1 3]
 [4 3 4]
 [4 0 2]
 [3 1 4]
 [3 1 1]
 [2 3 1]
 [3 3 0]
 [1 2 0]
 [4 0 3]]
[[3 1 0]
 [1 1 3]
 [4 3 4]
 [4 0 2]
 [3 1 4]
 [3 1 1]
 [2 3 1]
 [3 3 0]
 [1 2 0]
 [4 0 3]]
[[3 1 0]
 [1 1 3]
 [4 3 4]
 [4 0 2]
 [3 1 4]
 [3 1 1]
 [2 3 1]
 [3 3 0]
 [1 2 0]
 [4 0 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [21]:
A = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((A.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
A = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(A[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [23]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]
[[0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [26]:
x = np.random.uniform(0,1,10)
y = np.random.uniform(0,1,10)

np.einsum('i->', x)       
np.einsum('i,i->i', x,y) 
np.einsum('i,i', x,y)   
np.einsum('i,j->ij',x,y)

array([[0.16177886, 0.08548225, 0.30957092, 0.11143983, 0.01280647,
        0.19309233, 0.28003608, 0.06398599, 0.15868465, 0.01188571],
       [0.22908016, 0.12104355, 0.43835489, 0.15779969, 0.01813407,
        0.27342029, 0.39653333, 0.09060468, 0.22469873, 0.01683026],
       [0.45856565, 0.24230127, 0.87748541, 0.31587858, 0.03630022,
        0.54732437, 0.79376829, 0.18136967, 0.44979505, 0.0336903 ],
       [0.22551998, 0.11916238, 0.43154232, 0.15534729, 0.01785224,
        0.26917101, 0.39037072, 0.08919657, 0.22120664, 0.0165687 ],
       [0.40956693, 0.21641086, 0.78372421, 0.28212628, 0.03242146,
        0.48884158, 0.70895244, 0.16198993, 0.40173348, 0.03009042],
       [0.11018518, 0.05822069, 0.21084415, 0.07590001, 0.0087223 ,
        0.13151232, 0.19072841, 0.04357991, 0.10807776, 0.00809518],
       [0.21115667, 0.11157296, 0.4040575 , 0.14545326, 0.01671524,
        0.25202757, 0.36550811, 0.08351566, 0.20711805, 0.01551344],
       [0.01833381, 0.00968739, 0.0350825

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [28]:
pi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*pi*np.cos(pi)
y = a*pi*np.sin(pi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)              
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)
print(x_int)
print(y_int)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [29]:
a = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
b = np.logical_and.reduce(np.mod(a, 1) == 0, axis=-1)
b &= (a.sum(axis=-1) == n)
print(a[b])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [31]:
a = np.random.randn(100)
n = 1000 
idx = np.random.randint(0, a.size, (n, a.size))
m = a[idx].mean(axis=1)
con = np.percentile(m, [2.5, 97.5])
print(con)

[-0.21757676  0.19433591]
